### ISSUE TITLE
Compile and instal Fails on Raspberry Pi - 'urlshorten'

### ISSUE THREAD

**Issue by Navneet-Suresh** [timvisee/ffsend#104]
**OS Details:**
```
pi@raspberrypi:~/ffsend $ neofetch
  `.::///+:/-.        --///+//-:``    pi@raspberrypi
 `+oooooooooooo:   `+oooooooooooo:    --------------
  /oooo++//ooooo:  ooooo+//+ooooo.    OS: Raspbian GNU/Linux 10 (buster) armv7l
  `+ooooooo:-:oo-  +o+::/ooooooo:     Host: Raspberry Pi 3 Model B Rev 1.2
   `:oooooooo+``    `.oooooooo+-      Kernel: 4.19.75-v7+
     `:++ooo/.        :+ooo+/.`       Uptime: 23 hours, 20 mins
        ...`  `.----.` ``..           Packages: 1427 (dpkg)
     .::::-``:::::::::.`-:::-`        Shell: bash 5.0.3
    -:::-`   .:::::::-`  `-:::-
   `::.  `.--.`  `` `.---.``.::`
       .::::::::`  -::::::::` `
 .::` .:::::::::- `::::::::::``::.
-:::` ::::::::::.  ::::::::::.`:::-
::::  -::::::::.   `-::::::::  ::::
-::-   .-:::-.``....``.-::-.   -::-
 .. ``       .::::::::.     `..`..
   -:::-`   -::::::::::`  .:::::`
   :::::::` -::::::::::` :::::::.
   .:::::::  -::::::::. ::::::::
    `-:::::`   ..--.`   ::::::.
      `...`  `...--..`  `...`
            .::::::::::
             `.-::::-`

```
**Kernel:** Linux raspberrypi 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
**Release:** 
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Cargo Version:** cargo 1.40.0 (bc8e4c8be 2019-11-22)

**Compile features**

**Cargo.toml** : https://privatebin.net/?8775edb5db7e3fe8#2SPcmNKYfMPFhWKvisjSgXKJAMw9eXE3CDefARKiuSz2

**Build Error :** https://privatebin.net/?2c93f2c7e6c3edf6#AZqMwovbeRPumBstRAWwcobbiD3nMzyfKZYbRsFQRnW3

**Build is completed** if I disable "urlshorten".

**Log:** : https://privatebin.net/?2aa044af1267b246#GbaVU4EbrspT5MT8c3Lki8KUDbeF78UZ5KMzZbjZUvBL

**Cargo.toml File :** 
https://privatebin.net/?17af23d990a411ce#H1jmYDu27LPcJDUgQ64FcGkm8WQ3aNXioF4XL3kFq2qi

**Comment by timvisee** [comment]
This issue is tracked over on GitLab: https://gitlab.com/timvisee/ffsend/issues/94

**Comment by timvisee** [comment]
Fixed. See GitLab for details: https://gitlab.com/timvisee/ffsend/issues/94#note_265632216
