### ISSUE TITLE
[Feature] Login to send 1GB < files < 2.5GB 

### ISSUE THREAD

**Issue by Raketenphysik** [timvisee/ffsend#105]
Nothing more to say.

Very fine piece of software. Apprechiate your effort. Thank you!

Rgrds,

Mark

**Comment by timvisee** [comment]
Sadly, this is currently blocked by Mozilla. See the following issue 
over on GitLab for reference:

https://gitlab.com/timvisee/ffsend/issues/58

 > Very fine piece of software. Apprechiate your effort. Thank you!

Thank you!

**Comment by Raketenphysik** [comment]
Argh ... this is annoying. Hope they will make up their mind!
Rgrds, Mark
