### ISSUE TITLE
Windows: Failing with missing libssl and libcrypto

### ISSUE THREAD

**Issue by arunsathiya** [timvisee/ffsend#106]
I installed `ffsend` with `scoop` and the installation was successful. Trying to use the `ffsend u` command though is failing with this error:

```
The code execution cannot proceed because libssl-1_1-x64.dll was not found. Reinstalling the program may fix this problem.
```

Followed by,

```
The code execution cannot proceed because libcrypto-1_1-x64.dll was not found. Reinstalling the program may fix this problem.
```

I tried removing `ffsend` and installing it afresh, but that did not help. Should I install these packages/libraries manually, or is it something that `ffsend` installation should take care of?

**Comment by timvisee** [comment]
Thank you for the report.

Scoop should take care of installing the OpenSSL (libssl, libcrypto) dependency indeed. The OpenSSL package did not have any updates for a while, nor did I receive a report like this yet.

I'm wondering whether the installation did complete successfully. What Windows version are you using, and is it up-to-date? Also, is your scoop installation up-to-date?

For reference:  
`ffsend` package: https://github.com/ScoopInstaller/Main/blob/master/bucket/ffsend.json  
`openssl` package: https://github.com/ScoopInstaller/Main/blob/master/bucket/openssl.json

**Comment by arunsathiya** [comment]
Thanks for taking a look, @timvisee. I am using Windows 10.0.18362 Build 18362. Yes, it's latest.

Scoop is latest as well, because I installed it for the first time yesterday. And immediately tried installing `ffsend`, when it failed with this error.

I am not sure what I must do with the links that you had provided, but I guess I can ignore them.

**Comment by tonyxwz** [comment]
@arunsathiya You need to have `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` on the `PATH`. Scoop doesn't do that automatically. 

You could file a PR in the manifest of `openssl` here:
https://github.com/ScoopInstaller/Main/edit/master/bucket/openssl.json
and add this below `env_add`:

```
    "env_add_path": [
        "bin"
    ],
```

**Comment by timvisee** [comment]
@arunsathiya Sorry for the delay, I've been busy. A friend of mine confirmed that this is indeed a problem. You can ignore the linked JSON files.

@tonyxwz Thanks for this! Are you sure `PATH` is the right variable for Windows to search library files in? In any case, I'll submit a PR for it right now.

**Comment by timvisee** [comment]
I believe the relevant `scoop` package had just been updated now, which should solve this if I'm right.

I'm not quite sure how to update your `scoop` installation and the relevant package (`openssl`).

One of the following commands might do the trick: 
```bash
scoop update
scoop update openssl
```

Please let me know if this solves the issue you were having.

**Comment by tonyxwz** [comment]
Problem solved

**Comment by arunsathiya** [comment]
Sorry about the delay, @timvisee. It took a while to figure out that I had to update `openssl` using `scoop update openssl` on the administrator mode of command prompt.

All good now, thank you for your quick fix!

**Comment by timvisee** [comment]
Awesome. Good to hear it works now. Thanks for the heads up about Administrator mode.
