### ISSUE TITLE
libssl-1_1-x64.dll was not found

### ISSUE THREAD

**Issue by witwall** [timvisee/ffsend#107]
run ffsend-v0.2.58-windows-x64-static.exe on Windows 10 got the following error,

![image](https://user-images.githubusercontent.com/3222056/75836949-65402380-5dfe-11ea-8cc8-dbde10a95b8f.png)

**Comment by witwall** [comment]
after copy libssl-1_1-x64.dll and libcrypto-1_1-x64.dll, it works

**Comment by timvisee** [comment]
Yes, you've to manually install OpenSSL along with this for it to work. Good to see you've figured this out yourself. The `scoop` package does this automatically.

**Comment by witwall** [comment]
for static version, why not link openssl statically? and here is a ref,

[Is it possible to link libssl statically when using cargo? #183](https://github.com/sfackler/rust-openssl/issues/183)

**Comment by timvisee** [comment]
This is indeed what I'm doing for the static Linux binary. But I don't think this works for the Windows platform.
