### ISSUE TITLE
How to login?

### ISSUE THREAD

**Issue by LencoDigitexer** [timvisee/ffsend#110]
Hello, i try login in send.firefox.com via basic-auth. Writing in windows console:
ffsend.exe upload text.txt --basic-auth username@gmail.com:123abc
and i get a problem with downloads limit( if write --downloads over 1) and in my account in send.firefox.com dont show last downloads.

I try with quotation marks --basic-auth "username@gmail.com:123abc", but it doesn't work

**Comment by timvisee** [comment]
The `--basic-auth` is for HTTP basic authentication. This is different from Firefox Account authentication.

Sadly, logging in with your Firefox Account to increase limits is currently not possible through `ffsend`. This feature is blocked by Mozilla at this moment. Please refer to the following issue for more information:
https://gitlab.com/timvisee/ffsend/-/issues/58

The HTTP basic authentication system can be used if you're hosting your own Firefox Send instance behind a proxy with a password. Thus this has nothing to do with Firefox accounts.

I'll close this issue now. Feel free to ask any other questions that might come up.
