### ISSUE TITLE
How to install - IPKG package

### ISSUE THREAD

**Issue by AlphaC0de** [timvisee/ffsend#111]
I'm trying to install ffsend on an old NAS (My Book Live) that supports IPKG; how can I install this, I haven't seen an IPKG prebuilt option to download

**Comment by timvisee** [comment]
I'm not familiar with IPKG.

Is using a raw [binary](https://github.com/timvisee/ffsend/releases) an option (that you manually install), or is it being packaged as IPKG required?

**Comment by timvisee** [comment]
Sadly I don't have time available to set up an IPKG package. I'm simply assuming now that manually using a binary is a valid option.

If using a binary is not possible, if you have another question, or if someone else would like to give it a go; please post a comment to open the issue again.
