### ISSUE TITLE
new release with updated deps?

### ISSUE THREAD

**Issue by ignatenkobrain** [timvisee/ffsend#112]
Would be cool if you could release a new version with latest dependencies, that would help me in updating bunch of things in Fedora.

**Comment by timvisee** [comment]
I may have time for this at the end of the day.

**Comment by timvisee** [comment]
I've just released `v0.2.60` will all dependencies updated.

It should be available once this release pipeline succeeds: https://gitlab.com/timvisee/ffsend/pipelines/144901458

**Comment by timvisee** [comment]
I'm publishing `v0.2.61` instead due to some error: https://gitlab.com/timvisee/ffsend/pipelines/144921569
