### ISSUE TITLE
CLI and doc shall clarify, Firefox Authentication is not available yet

### ISSUE THREAD

**Issue by vlcinsky** [timvisee/ffsend#116]
There are currently 8 closed issues (#110, #100, #77, #67, #22, #20, #17) related to the fact, Firefox Authentication (FxA) is not implemented yet and that `--basic-auth` option is related to protected reverse proxy and not to FxA.

# TOC
- Current status
  * Firefox Authentication is not available yet
  * Option --basic-auth has nothing to do with FxA
  * There is currently no way to upload file as authenticated user
  * Documentation of --basic-auth does not clarify, it is not FxA related feature
- Proposed solution
  * Extended CLI help doc for `--basic-auth`
  * README.md
    + Intruductory text
    + Places talking about `--basic-auth`
  * Open issue, related to missing Firefox Authentication

# Current status
From these issues it is clear that:

## Firefox Authentication is not available yet
There are technical problems with using Firefox Authentication and they are well covered in https://gitlab.com/timvisee/ffsend/-/issues/58

It seems, that until Firefox does not change their mind in regards to allowing other registered application to take advantage of it, it is not possible to interact with Firefox Send web service using FxA.

## Option --basic-auth has nothing to do with FxA

Seeing username and passoword in an option, it is easy to get confused and think, this relates to FxA.

In fact, this is not related at all as it allows to specify username and password for protected reverse proxy.

## There is currently no way to upload file as authenticated user

There are many options, which are relevant only when interacting with the service as authenticated user.

Unfortunately, as there is no way to authenticate via FxA, these options are mostly irrelevant.

Note: Statememnts above are related to https://send.firefox.com and are subject to limits (max number of downloads and expiration time for annonymous users) set to this service by Mozilla. I think, even running it's own Firefox Send instance only allows intereaction as annonymous user.

## Documentation of --basic-auth does not clarify, it is not FxA related feature
Current CLI documentation states in the OPTIONS section:

    --basic-auth <USER:PASSWORD>
        HTTP basic authentication credentials [env: FFSEND_BASIC_AUTH]

# Proposed solution
The fact, FxA is not available yet, shall be clearly stated in every context, it seems relevant. This shall prevent confusion and also minize number of issues, which are repeatedly resulting from (currently) false expectations.

Following forms are proposed:
- extend CLI help doc for `--basic-auth`
- README
- issue, which will stay open, until FxA is available

## Extended CLI help doc for `--basic-auth`
E.g.:

    --basic-auth <USER:PASSWORD>
        Protected proxy HTTP basic authentication credentials (not FxA) [env: FFSEND_BASIC_AUTH]

### Intruductory text
Current introductory text is overstatement:

    # ffsend

    > Easily and securely share files from the command line.
    > A fully featured [Firefox Send][send] client.

    Easily and securely share files and directories from the command line through a
    safe, private and encrypted link using a single simple command.
    Files are shared using the [Send][send] service and may be up
    to 1GB (2.5GB authenticated). Others are able to download these files with this tool, or through
    their web browser.

It shall better read:

    # ffsend

    > Easily and securely share files from the command line.
    > [Firefox Send][send] client (not authenticated only at the moment).

    Easily and securely share files and directories from the command line through a
    safe, private and encrypted link using a single simple command.
    Files are shared using the [Send][send] service and may be up
    to 1GB. Others are able to download these files with this tool, or through
    their web browser.

It may even link to relevant issue, explaining current status of FxA implementation.

### Places talking about `--basic-auth`
All places talking about `--basic-auth` shall use the 

> Protected proxy HTTP basic authentication credentials (not FxA)

wording.

## Open issue, related to missing Firefox Authentication
There shall exist one issue (this one or another one), explaining the problem with FxA and allowing to track it's development.

The issue shall stay open until it is resolved.

**Comment by timvisee** [comment]
I've had a quick read to this issue and I agree this is confusing. Your suggested documentation/description changes seem reasonable, so feel free to submit a PR for this.

I'm currently busy, but I'll try to look into this further tomorrow. I might give contacting Mozilla about this a try again as well.

**Comment by vlcinsky** [comment]
Shall be resolved by PR #117

**Comment by brightly-salty** [comment]
I'm guessing this should be closed, as PR #117 has been merged.
