### ISSUE TITLE
Line break required before printing URL

### ISSUE THREAD

**Issue by igitur** [timvisee/ffsend#122]
Hi,

Using this from Windows 10. ffsend v0.2.66. 

When I upload a file, the resulting URL is split over 2 lines. Screenshot:
![image](https://user-images.githubusercontent.com/145854/93982849-14841e00-fd82-11ea-880e-9fc6fccbea05.png)

**Comment by igitur** [comment]
PS: Nothing interesting to see in the uploaded file, but they curious ones are welcome to check it out.

**Comment by timvisee** [comment]
Thanks for the report!

Not sure what is going on here. It might have something to do with the way the progress bar is rendered and how line endings work on Windows.

Could you check if the same happens in a powershell window?

I'll attempt to take a further look into this later today.

**Comment by igitur** [comment]
Same issue in Powershell. I tried to inspect the source, but couldn't even figure out where the line break is printed. Maybe this is a good first issue to learn Rust. 

Sidenote: What IDE do you use for Rust dev?

**Comment by timvisee** [comment]
Yea, feel free to give it a try and submit a PR!

The 'Upload complete' message is part of the progress bar/progress reporting logic. This message replaces the progress bar on completion. This is done through the `pbr` library. The completion message is print here:
https://github.com/timvisee/ffsend/blob/3a90b0b0b1b787c9170afa934f884326c14ca908/src/progress.rs#L65

The URL is print as a table, nicely align stuff when more details are printed. So this is a little more complex. The URL is added to the table here:
https://github.com/timvisee/ffsend/blob/3a90b0b0b1b787c9170afa934f884326c14ca908/src/action/upload.rs#L394

Adding a newline character somewhere might do the trick.

I'm not really using an IDE. Using Vim at the moment.

**Comment by timvisee** [comment]
Would you mind to test a patch for this, assuming you've already installed Rust?

```bash
git clone https://gitlab.com/timvisee/ffsend.git
cd ffsend

git checkout 104-fix-share-url-printing-on-windows

cargo build --release
cargo run --release -- upload FILE
```

This prints the 'Upload complete' message on a newline on Windows platforms.

**Comment by timvisee** [comment]
This issue has been mitigated. See https://gitlab.com/timvisee/ffsend/-/issues/104
