### ISSUE TITLE
I seem to be quite stupid... Sorry...

### ISSUE THREAD

**Issue by raphaelritz** [timvisee/ffsend#123]
I am currently trying to install ffsend (thank you very much for making it) on android using termux. I inputted the command `pkg install ffsend`, but termux does not appear to be able to find the package and displays
`$ pkg install ffsend
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package ffsend`

Which is why I am now in need of assistance.

**Comment by timvisee** [comment]
Hi there. The Termux package is managed by their community. It might have been removed when Mozilla announced they'd stop with Send.

I'm unsure if this is the case, but it seems likely. I might be able to take a look into this tomorrow.

**Comment by raphaelritz** [comment]
Thank you very much for your answer and the work you put into this project :)
I didn't know who manages this package or termux packages in general, I am sorry to have wasted your time :(

**Comment by timvisee** [comment]
No problem at all!

You can probably compile it yourself for Termux, but I don't know the steps to do so.

**Comment by raphaelritz** [comment]
Yes I believe I believe I can compile it into a *.deb file and install it manually.
:)
