### ISSUE TITLE
Add another parameter to the ws API

### ISSUE THREAD

**Issue by dylangerdaly** [timvisee/ffsend#132]
Hi,

I've added a `password` string to the ws API, the server uses this to either allow or deny the upload, I can't seem to see where this data is sent via ffend.
![Screenshot_2021-11-22_10-25-50](https://user-images.githubusercontent.com/7969682/142785268-6d513b23-ca87-4845-871a-6a9719d4cd6d.png)

This works great with the JS version of Send however I can't seem to add this to `ffsend`

The string `dlimit` doesn't even exist in the ffsend repo?

I assume I'd need to add it here -> https://github.com/timvisee/ffsend/blob/master/src/action/upload.rs#L338

**Comment by timvisee** [comment]
> The string `dlimit` doesn't even exist in the ffsend repo?
>
> I assume I'd need to add it here -> https://github.com/timvisee/ffsend/blob/master/src/action/upload.rs#L338

`ffsend` is broken up into two parts. This CLI repository, and the API crate [`ffsend-api`](https://github.com/timvisee/ffsend-api).

The `dlimit` property is set within the API crate, which explains why you couldn't find it in this repository.

This CLI application starts the upload [here](https://github.com/timvisee/ffsend/blob/216772361a84b17138512b1c7781caaa4e44bca7/src/action/upload.rs#L372-L380), after which the API crate handles the actual upload.

- The API uploads here: https://github.com/timvisee/ffsend-api/blob/744c8d48fdd24c25f7e025ac81aca0f55e1c7728/src/action/upload.rs#L318-L421
- For the upload, a 'file info' object is constructed here: https://github.com/timvisee/ffsend-api/blob/744c8d48fdd24c25f7e025ac81aca0f55e1c7728/src/action/upload.rs#L173-L190
- The `FileInfo` struct sent over the websocket is defined here: https://github.com/timvisee/ffsend-api/blob/744c8d48fdd24c25f7e025ac81aca0f55e1c7728/src/file/info.rs#L6-L40

This is somewhat messy, sorry for that. I never had the time to properly clean things up.

**Comment by dylangerdaly** [comment]
Fantastic, thank you, I'll play with this today!

Nice job on all of this btw :+1:

**Comment by timvisee** [comment]
Thanks! Feel free to post here if you need any further guidance.
