### ISSUE TITLE
Error In Termux: Android

### ISSUE THREAD

**Issue by noormohammedb** [timvisee/ffsend#135]
after installing with `pkg install ffsend`

**CANNOT LINK EXECUTABLE "ffsend": library "libssl.so.3" not found: needed by main executable**

f-droid release of termux with v0.118.0 (118)

> `termux-info`                    

Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
apt/stable 2.3.15-1 aarch64 [upgradable from: 2.3.15]
termux-tools/stable 0.167 all [upgradable from: 0.163]
vim-python/stable 8.2.4450-2 aarch64 [upgradable from: 8.2.4450]
vim-runtime/stable 8.2.4450-2 all [upgradable from: 8.2.4450]
wget/stable 1.21.3-1 aarch64 [upgradable from: 1.21.1-1]
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-g961f862 #1 SMP PREEMPT Mon Jun 7 00:49:28 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9 Pro

**Comment by timvisee** [comment]
You're likely better of posting this in a termux issue, as the package is managed by them.

Is there an `openssl` package you can install? That might fix this issue for now.

**Comment by noormohammedb** [comment]
it solved after installing openssl
`pkg install openssl`
