### ISSUE TITLE
ffsend scoop package is ready to use.

### ISSUE THREAD

**Issue by h404bi** [timvisee/ffsend#18]
> A chocolatey and a scoop package along with an .msi installer will be coming soon.

[Just FYI](https://github.com/lukesampson/scoop/pull/3213).

**Comment by timvisee** [comment]
Cool, thanks for the heads up!

I'd like to automate scoop releases through CI though. So I don't have to push updates manually each time.

That's something I might work on at a later time.

**Comment by h404bi** [comment]
@timvisee 
Scoop with automatically updates the package recipe when you publish a new version of ffsend on GitHub releases. So you don't need to warry about the updates when you uploading new binaries. ([ffsend package history](https://github.com/lukesampson/scoop/commits/master/bucket/ffsend.json))

**Comment by timvisee** [comment]
@h404bi That's brilliant, thanks a lot!

**Comment by linsui** [comment]
Scoop will install openssl 1.1.1d but readme say that 1.1.0j is needed.

**Comment by timvisee** [comment]
@linsui Anything having the version number `1.1.0` or `1.1.1` should work.

**Comment by linsui** [comment]
Thanks!
