### ISSUE TITLE
Shorten URLs and render QR codes

### ISSUE THREAD

**Issue by apsknight** [timvisee/ffsend#19]
Currently, the download file link generated by this utility is very big and it is very hard to share the link verbally with the person sitting right beside.

The idea is to add an URL shortener with this utility which can generate a temporary shortened link of the original link based on user input. The shortened link may be flushed after a certain time interval so that it can be reused to share another file later by somebody else.

**Comment by timvisee** [comment]
I like the idea. However, the link being this long is one of the major things that keeps your files secure, as the actual file key is contained in it.
Shortening a link through a 3rd party service would leak your secure link to them, requiring you to trust this third party they're handling your shortened link properly. This would also break the the 'end-to-end' encryption aspect.

I'd like to emphasize that the current link is produced by [Firefox Send](https://send.firefox.com/) which is where your files are uploaded at. `ffsend` is just an interface to this service, which passes the link along. If you were suggesting that the Firefox Send service itself should provide shortened links, you should ask it over [there](https://github.com/mozilla/send/issues), but I assume they'll give a similar response.

For `ffsend` itself I think the only option would be to use a 3rd party shortening service, of which I don't think it's a good idea security wise.

**Comment by mohamedanees6** [comment]
I agree with you @timvisee. But still, I'd love to have that feature as an optional value. 

Maybe if I am sharing any not so important file. I'd care less on the security aspect. 

I'd say we can safely trust bitly(or any alternates) which millions of people use everyday.

**Comment by timvisee** [comment]
I agree, a feature like this would be cool.

You know what, I'm fine with implementing it. I'll create an implementation issue for it at the end of the day. I don't have an estimate for when it's ready though, there are quite some other things I've to do.

It can probably be enabled with a `--shorten` flag while uploading. A security warning will be showed to the user, unless `--yes` or `--force` is given. And I'll probably define a compiler feature flag for it, so `ffsend` can be compiled without support for it (some people might prefer that in a secure environment).

**Comment by eloydegen** [comment]
Another idea I came up with: generating a QR code of the URL. But that would only be useful when transferring the file to a destination devices that has a camera, such as a smartphone. But it would be more secure than using a 3th party URL shortener.

**Comment by timvisee** [comment]
I created the following implementation issues over at GitLab for these ideas:
- URL shortener: https://gitlab.com/timvisee/ffsend/issues/68
- QR code: https://gitlab.com/timvisee/ffsend/issues/69

I recommend following those for updates on any progress.

@eloydegen Yes, brilliant idea. I've created an implementation issue as listed above.

I'll keep this issue open until URL shortener support is implemented.

**Comment by timvisee** [comment]
QR code support has been implemented in 6d58e5efe373cee4db370a004c0ed82aad569197, and will be part of `v0.2.31`

Here's an example:
![image](https://user-images.githubusercontent.com/856222/54391986-bebbb980-46a6-11e9-812e-a606a862aeb4.png)

**Comment by timvisee** [comment]
@apsknight @mohamedanees6 @eloydegen URL shortening has now been implemented as well!

You can use the `--short` (`-S`) flag to shorten an URL while uploading.
Currently the `is.gd` service is used for shortening (because this doesn't require an API token), the used service might change in the future.

```bash
ffsend upload my-file.txt -S
```

This was introducted in 866579c80bcfa16206d832ff4f1f4a0f5d47e196, and will be in `v0.2.32`.
You should be able to use this new version once this release pipeline succeeds:
https://gitlab.com/timvisee/ffsend/pipelines/51941736

**Comment by apsknight** [comment]
Thank You @timvisee for quick implementation of these features.

**Comment by UnixCro** [comment]
This QR function saves a lot of time.  Thank you man i kiss your heart
