### ISSUE TITLE
HTTP Authentication

### ISSUE THREAD

**Issue by GHQB** [timvisee/ffsend#22]
Dear Tim Visée,

thank you very much for developing ffsend!

I use it with send.firefox.com and now want to use it with my own server.

My server is behind a reverse proxy. All services behind that are protected from abuse by HTTP basic authentication (plus TLS).

I would be really grateful if ffsend could send/use HTTP basic auth credentials.

Probably the underlying rust library already implements this, it would be really nice if this could be exposed to the command line (and perhaps some ENVIRONMENT variable).

Hopefully not coming across as some lazy freeloader i would be grateful if this feature could be implemented, i might not be the only user of this :)

kind regards.

**Comment by timvisee** [comment]
Yes, this sounds doable. I'd be fine with implementing it. I'll take a look at what's possible later today, and notify this issue.

Thanks!

**Comment by timvisee** [comment]
I've created the following implementation issue for now which I recommend to follow for any progress updates:
https://gitlab.com/timvisee/ffsend/issues/70

I'll keep this issue open until it has been implemented.

**Comment by GHQB** [comment]
Thanks a lot! :)

**Comment by timvisee** [comment]
@GHQB I've just implemented basic HTTP authentication to use for a protected reverse proxy. This has been implemented in 12e660616468b931de2997e1278a7393aceb8c7e and will be part of [`v0.2.38`](https://github.com/timvisee/ffsend/releases/tag/v0.2.38). The release will be available as soon as this pipeline succeeds:
https://gitlab.com/timvisee/ffsend/pipelines/52649353

For now, I've added the `--basic-auth <USER:PASSWORD>` flag, and the environment variable `FFSEND_BASIC_AUTH` which uses the same format. I might automatically derive these credentials from the host or share URL in the future as well.

Here's an example command:
```bash
bash upload --basic-auth user:secret my-file.txt
```

I haven't truly tested the implementation on a protected reverse proxy, but I'm quite sure the implementation is correct. It would be awesome if you could give it a try, to confirm this is working.

Sorry that it took me a while.

**Comment by waldauf** [comment]
Hello @timvisee,

I set env variable `FFSEND_BASIC_AUTH=my@email.com:PasswordWith@Sign` and it's not possible for me to send the file to the server:
```
export FFSEND_BASIC_AUTH="my@email.com:PasswordWith@Sign"
ffsend upload --force --verbose -e 7d picture.jpg
error: failed to upload the specified file
caused by: failed to upload the file
caused by: got invalid response from server

For detailed errors try '--verbose'
For more information try '--help'
```
The `--verbose` switch didn't write more information to stdout. I tried to add `--basic-auth=my@email.com:PasswordWith@Sign` switch and no success too. 

Can I ask you for help what I do bad?

**Comment by waldauf** [comment]
Now I found your answer on [GitLab](https://gitlab.com/timvisee/ffsend/issues/58). So already it's not neccessary to answer me. :]

**Comment by timvisee** [comment]
Good to hear you found it. I'm sorry I'm not able to implement this until Mozilla accepts third-party applications.
