### ISSUE TITLE
Add Contribution guidelines

### ISSUE THREAD

**Issue by nagyf** [timvisee/ffsend#27]
Hi,

I think it would be a good idea to add contribution guidelines to the project: [Setting guidelines for repository contributors](https://help.github.com/en/articles/setting-guidelines-for-repository-contributors).

**Question**: I see you are using GitLab. Where should we contribute? On Github or Gitlab? E.g. this could also be written in the contribution guideline :)

**Comment by timvisee** [comment]
You're totally right. I haven't been able to write these guidelines yet.

In case you're wondering: the project is mainly hosted on [GitLab](https://gitlab.com/timvisee/ffsend), this GitHub repository is a mirror. I left the issue and pull request boards open here to make contributing more approachable for GitHub users.

Thank you for opening this issue. This is definitely something to look into.

**Comment by timvisee** [comment]
I've added the first stubs for the contribution guideline in: [`./docs/CONTRIBUTING.md`](https://github.com/timvisee/ffsend/blob/master/docs/CONTRIBUTING.md)

I'll close this issue now. I plan to improve this document in the future.
