### ISSUE TITLE
Remove Compiler Warnings

### ISSUE THREAD

**Issue by ingorichter** [timvisee/ffsend#29]
```
warning: unused import: `std::io::ErrorKind as IoErrorKind`
  --> src/util.rs:13:5
   |
13 | use std::io::ErrorKind as IoErrorKind;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default

warning: use of deprecated item 'failure::Fail::causes': please use the 'iter_chain()' method instead
  --> src/util.rs:51:10
   |
51 |         .causes()
   |          ^^^^^^
   |
   = note: #[warn(deprecated)] on by default
```

Saw these on my machine and think they should be fixed (seems to be easy though)

**Comment by timvisee** [comment]
You're totally right, thanks for the report!

The first warning seems to be an unused import on non-Linux systems which has recently been implemented. I'm no Linux thus I never noticed it. Fixed it in c8a854d492ecfa09208250a16df2cf13efb52a78.

The second warning that is shown (regarding `.causes()`) has been there for a while. It suggests using `.iter_chain()`, but that isn't a true replacement for it. I haven't had the time yet to patch this as I prioritized other things. I've created the following issue for it over on GitLab:
https://gitlab.com/timvisee/ffsend/issues/79

There might be some new warnings with non-default compiler [feature flags](https://github.com/timvisee/ffsend#compile-features--use-flags).
