### ISSUE TITLE
When compiling this warning comes out. Can I ignore it?

### ISSUE THREAD

**Issue by akimdi** [timvisee/ffsend#47]
When compiling this [warning](https://github.com/timvisee/ffsend/blob/master/src/util.rs#L58)  comes out. Can I ignore it?

`warning: use of deprecated item 'failure::Fail::causes': please use the 'iter_chain()' method instead`

![image](https://pp.userapi.com/c852224/v852224304/ff41a/KDRGmWWdfik.jpg)

**Comment by timvisee** [comment]
You're correct. You can ignore it for now. `ffsend` compiles and runs fine!

Yes, I do need to fix this some time. The replacement suggestion by the compiler isn't compatible with how it's currently used. Therefore it requires some refactoring to fix this issue. I haven't had time to take a look into it yet.

I'll close this issue for now.
It's tracked here: https://gitlab.com/timvisee/ffsend/issues/79
