### ISSUE TITLE
OpenSSL download link is down

### ISSUE THREAD

**Issue by sieunhando** [timvisee/ffsend#50]
This link is down xD. `https://slproweb.com/download/Win64OpenSSL_Light-1_1_0j.exe`. I found different link here: https://bintray.com/vszakats/generic/openssl

**Comment by timvisee** [comment]
Thank you for the report! I'll look up the correct link, or a link to a compatible version in a second.

**Comment by sieunhando** [comment]
okay :D

**Comment by timvisee** [comment]
Auch! In that case I assume `scoop` is using the same URL. I'll open an issue in the `scoop` package index for this as well.

**Comment by timvisee** [comment]
I've opened an issue for `scoop` here: https://github.com/lukesampson/scoop/issues/3429

The link you've shared ([bintray.com/.../openssl](https://bintray.com/vszakats/generic/openssl)) does indeed provide the correct OpenSSL version. However, it does not provide an easy to use installer. I'll try and find the installer in cache on one of my systems to host it myself for the time being.

**Comment by sieunhando** [comment]
Nice bro :+1:

**Comment by timvisee** [comment]
Yes. Found a copy!

You can use this link for now: https://u.visee.me/dl/openssl/Win64OpenSSL-1_1_1b.exe

I'll update the README in a second, and continue the discussion regarding `scoop` in the linked issue. Will close this issue now.
