### ISSUE TITLE
Cargo.lock is out of date in v0.2.46

### ISSUE THREAD

**Issue by lilyball** [timvisee/ffsend#51]
The v0.2.46 release still lists `version = "0.2.45"` in Cargo.lock, meaning it can't be built with `--frozen`.

**Comment by lilyball** [comment]
I'm working around this with a local patch in my [Nix PR](https://github.com/NixOS/nixpkgs/pull/60945) but perhaps you should update your release process to ensure you can run `cargo check --frozen` on a clean checkout.

**Comment by timvisee** [comment]
Whoops, it seems you're right.
I won't be releasing a new version just for this, I'll try to make sure it's correct in `0.2.47`.

I'll add `cargo check --frozen` into the pipeline now.

Sorry for the delay.
