### ISSUE TITLE
Firefox Send limit 1GB

### ISSUE THREAD

**Issue by sieunhando** [timvisee/ffsend#67]
Hi, I think Firefox Send is limit 1GB for now, not 2GB anymore :D

**Comment by akimdi** [comment]
> Hi, I think Firefox Send is limit 1GB for now, not 2GB anymore :D

for registered users 2.5 GB

**Comment by timvisee** [comment]
> Hi, I think Firefox Send is limit 1GB for now, not 2GB anymore :D

I assume you're referring to what is noted in the README.

Thanks for the note, I'll close this issue now and make the change after it.

> > Hi, I think Firefox Send is limit 1GB for now, not 2GB anymore :D
> 
> for registered users 2.5 GB

Yes. I'm currently not able to provide support for Firefox Account (FxA) authentication, thus the practical limit will remain 1GB for now.
