### ISSUE TITLE
I have trouble with authentication

### ISSUE THREAD

**Issue by Simon-Laux** [timvisee/ffsend#77]
```
ffsend upload --downloads 20 --api - --basic-auth "user:password"  README.md
```
Doesn't work for me - it asks me to authenticate:
```
The downloads limit must be one of: 1
Use '--force' to force, authenticate for higher limits
```
Is this the right way to authenticate or is this only for proxies?

**Comment by timvisee** [comment]
The `--basic-auth` option is indeed just for HTTP proxies.

Sadly, I'm not able to implement Firefox Account (FxA) through OAuth at this moment, as Mozilla doesn't allow 3rd party application registrations yet. I'm currently messaging with Mozilla employees about this.

Until then, I'm afraid you have to use the Firefox Send website instead for increased download limits.

For progress on Firefox Account integration, please follow: https://gitlab.com/timvisee/ffsend/issues/58

**Comment by Simon-Laux** [comment]
I wanna use ffsend in a irc bridge bot to upload images/files and send a link to irc. So using the website would be unsuitable. 
Seems like I have to wait with that until Mozilla allows it.
I'll subscribe to your issue over on gitlab.

**Comment by timvisee** [comment]
> I wanna use ffsend in a irc bridge bot to upload images/files and send a link to irc. So using the website would be unsuitable.
> Seems like I have to wait with that until Mozilla allows it.
> I'll subscribe to your issue over on gitlab.

Sounds like an awesome implementation! I'm sorry I'm not in the position to improve this situation. I'm eagerly waiting for any good news.

**Comment by timvisee** [comment]
I'd like to add that you can host your own Firefox Send web instance as a workaround, if you'd like. A `--host` option (or `FFSEND_HOST`) is available for uploading to a custom host. You can set any download limit on your own instance. Though I assume this isn't what you're looking for.

> I wanna use ffsend in a irc bridge bot to upload images/files and send a link to irc. So using the website would be unsuitable.
> Seems like I have to wait with that until Mozilla allows it.
> I'll subscribe to your issue over on gitlab.

Sounds like an awesome implementation! I'm sorry I'm not in the position to improve this situation.

**Comment by Simon-Laux** [comment]
_The whole point is that I don't host the files myself..._ :wink:
The feature in my bot can wait, I think It'll be worth it.
