### ISSUE TITLE
Roadmap file mentioned in README is missing

### ISSUE THREAD

**Issue by KRMcGuire** [timvisee/ffsend#8]
The README for the project mentions a roadmap file:

https://github.com/timvisee/ffsend/blob/master/ROADMAP.md

But no such file exists. It'd be cool to view the roadmap for this project, it sounds super interesting.

**Comment by timvisee** [comment]
Thanks for the heads up! I must have removed it a while back.

In the mean time, you can check out the issue list over at GitLab for features I probably want to implement:
https://gitlab.com/timvisee/ffsend/issues

I'm currently focusing on releasing proper packages and binaries for common platforms though, and will be polishing the README. After that I'll probably start on implementing Firefox Account support to allow higher download counts and longer expiry times.

I'll probably remove the reference from the README for now once I have time, and might compile a new roadmap list based on the current issues at a later time.

**Comment by timvisee** [comment]
It appears I've fixed this some time ago.
