### ISSUE TITLE
Compressed file compatibility 

### ISSUE THREAD

**Issue by DARKFiB3R** [timvisee/ffsend#9]
Solid Explorer (Android) can't handle the .zip files created by Firefox Send.

.zip files created by 7-Zip are fine.

Turns out Solid Explorer can't handle .rar or .7z files either.

**Comment by timvisee** [comment]
If you've a comment on the `.zip` files generated by send.firefox.com, I recommend you to submit an issue over at: https://github.com/mozilla/send/issues

Currently `ffsend` only supports creating `.tar` archives (which you can use by providing the `--archive` flag while uploading). I am planning to add support for `.zip` and other archive types soon, as the newly released Firefox Send version uses `.zip` files as well.

I'm not quite sure what you're asking here though. Did the above answer your question, or is there some other problem?

**Comment by DARKFiB3R** [comment]
Not sure how I mistakenly found myself here. Thank you for providing the correct link.
