### ISSUE TITLE
Configuration options

### ISSUE THREAD

**Issue by vfazio** [timvisee/ffsend#97]
I'm considering spinning up a local Send instance internally for filedrops and was hoping to use ffsend as the cli. One thing I'm wondering is how difficult it'd be to use environment vars or a config file for things that would be tuned in an enterprise scenario, such as the target Send host.

explicit command line options would override inherited config options.

While we could recompile the source with our host hardcoded in, i was hoping to not have to maintain an internal fork and continually rebase on top of your work.

**Comment by timvisee** [comment]
Yes, you can use an environment variable to set the default target host like this:

```bash
export FFSEND_HOST=https://send.example.com/
```

Explicitly passing `--host` to the CLI would override the environment variable value.

See the configuration section in the README for more details:  
https://github.com/timvisee/ffsend#configuration-and-environment

Does this answer your question, and is this good-enough?

**Comment by vfazio** [comment]
wow, i feel like a complete idiot. I must've completely glossed over that section. Yea, this should be fine since we can just deploy the export into our bash profiles.

sorry for the noise
