### ISSUE TITLE
ability to specify download expiration time

### ISSUE THREAD

**Issue by iomintz** [timvisee/ffsend#98]
on the website, you can choose how _long_ before an upload expires, defaulting to one day:
![screenshot of the expiration time picker](https://user-images.githubusercontent.com/538336/66283797-8837cd00-e88a-11e9-8802-bf3c9278b0a7.png)
It would be nice if we could choose another expiry, perhaps in seconds or minutes, or whatever the API allows. It should be a flag for both `ffsend upload` and `ffsend params`.

**Comment by timvisee** [comment]
Yes, that's a nice addition!

In fact, I actually thought this was already part of the CLI, but after closer inspection I'm seeing it isn't. For what I know the expiry time must be any of the time units in the screenshot provided, so `ffsend` would have to choose the nearest time unit when you'd enter `--expire 3h`.

I'm not sure when I'm able to work on this feature. If someone else wants to give it a try, go for it!

Thanks for the suggestion.

**Comment by timvisee** [comment]
Linking related issue over on GitLab:
https://gitlab.com/timvisee/ffsend/issues/85

**Comment by timvisee** [comment]
It took me some time, but this has now been implemented, and is released as part of `v0.2.54`.

You'll now be able to set the expiry time to 5 minutes, for example:

```bash
ffsend upload my-file.txt --expiry 5m
```

See `ffsend help upload` for more details.
