### ISSUE TITLE
How can I use my own host?

### ISSUE THREAD

**Issue by bookug** [timvisee/ffsend#99]
How to build one?  like firefox send?

**Comment by timvisee** [comment]
There's instructions on the official [Firefox Send GitHub](https://github.com/mozilla/send/blob/master/README.md) on how to host your own instance. You might use Docker for that.

Then use the `--host` flag like:

```bash
ffsend upload my-file.txt --host https://myhost.com/
```

Or set your custom Send host in the `FFSEND_HOST` environment variable.
See [this](https://github.com/timvisee/ffsend/blob/master/README.md#configuration-and-environment) section for more information.
